#include<iostream>
using namespace std;

int main(){
    // cout<<"Hello world\n"<<endl<<"hello aman"<<endl;
    // cout<<3+2<<endl;
    // cout<<"3+2";
    //variable declaration
    // int a=10,b=20,c=40,d=44;
    
    // cout<<a+b+c; 

    // char ab ='z';
    // cout<<ab;
    // cout<<'b';
    // cout<<"m";


// float f = 1.22;
// cout<<f<<endl;

// double d = 9.887;
// cout<<d<<endl;
// bool b = false;
// cout<<b;
// bool a = true;
// cout<<a;

}